var i = {
    questionTypeList: [ {
        id: "0-0",
        category: 0,
        name: "购房资格",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    }, {
        id: "0-1",
        category: 0,
        name: "贷款须知",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    }, {
        id: "0-2",
        category: 0,
        name: "买房困惑",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    }, {
        id: "0-3",
        category: 0,
        name: "楼盘对比",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    }, {
        id: "0-4",
        category: 0,
        name: "刚需",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    }, {
        id: "0-5",
        category: 0,
        name: "摇号",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    }, {
        id: "0-6",
        category: 0,
        name: "落户",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    }, {
        id: "0-7",
        category: 0,
        name: "其他",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !0,
        size: "mini"
    } ],
    questionStatusList: [ {
        id: "1-1",
        status: 0,
        category: 1,
        name: "未回答",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !1,
        size: "default"
    }, {
        id: "1-2",
        status: 1,
        category: 1,
        name: "已回答",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !1,
        size: "default"
    }, {
        id: "1-3",
        status: 2,
        category: 1,
        name: "已解决",
        isActived: !1,
        isConfirm: !1,
        canMultiple: !1,
        size: "default"
    } ],
    dropdownMenuList: [ {
        id: 0,
        name: "问题类型",
        type: "questionTypeList",
        isActived: !1,
        isSelected: !1,
        canMultiple: !0
    }, {
        id: 1,
        name: "全部",
        type: "questionStatusList",
        isActived: !1,
        isSelected: !1,
        canMultiple: !1,
        status: "",
        statusName: ""
    } ]
};

module.exports = i;